### ISSUE TITLE
Think about entry points

### ISSUE THREAD

**Issue by LucPrestin** [LucPrestin/Hidden-Modularity#2]
As someone looking into the hidden modularity, I'd like to know a few entry points from which I could start my research.

---

**Describe the solution you'd like**

For each of the following rough parts of squeak/smalltalk, there should be at least one entry point documented:
- User Input
- Graphics Output
- Network Access

---

## Conditions of satisfaction

- [x] Each of the rough parts has at least one entry point
- [x] There is a wiki page documenting the entry points
- [x] For each entry point there is an extra issue that is at least a rough idea on how to tackle it

**Comment by LinqLover** [comment]
(FYIO, in case you have not seen it yet, there is also a generic entry point in `TraceDebugger class >> #exampleWorldCyclesFor:` and you could extract a relevant subset of the trace afterward, e.g., using `#borderContexts:`. However, tracing entire world cycles is pretty slow right now ...)
