### ISSUE TITLE
Find entry point for network access

### ISSUE THREAD

**Issue by LucPrestin** [LucPrestin/Hidden-Modularity#8]
As someone looking into the hidden modularity, I'd like to have an entry point to look at in terms of network access

---

Derived from #2 

**Describe the solution you'd like**

Think about an easy use case that could be traced in order to gain some insight

**Hints & Thoughts**

- I currently don't have any knowledge about network access in squeak/smalltalk -> ask for help

**Comment by LinqLover** [comment]
> I currently don't have any knowledge about network access in squeak/smalltalk -> ask for help

The modern interface for network accesses is the WebClient package (classes `WebClient` and `WebServer`). There are even some tutorials about them in the Squeak help browser. :-)

**Comment by LucPrestin** [comment]
see #16
